config/routes.rb
Rails.application.routes.draw do
  get 'lands/index'
  post "lands/import"

  get 'kanchis/upload'
  post 'kanchis/upload_save'

  get 'owners/new'

  get 'welcome/index'

    resources :owners do
      resources :lands
    end
    resources :lands do
      member do
        get "kenri"
      end
    end
    resources :kanchis
    resources :kan_hyokas
    resources :kanchi_henkos
    root 'welcome#index'

end

app/models/land.rb
class Land < ActiveRecord::Base
  require 'csv'

  self.primary_key = "f_code"
  has_many :children, class_name: "Land",
                      foreign_key: "f_code_parent"
  has_many :kanchis, foreign_key: "f_code"
#  has_one :owner, foreign_key: "sho_code"
  belongs_to :owner

  attr_accessor :horyu
  def initialize
    @horyu = nil
  end

  def self.import( file )
    CSV.foreach( file.path, headers: true ) do |row|
#pp row;exit
      h_rec = row.to_hash.slice(*updatable_attributes)
p h_rec
      fcode = h_rec["f_code"]
      next if fcode.nil?
      h_rec["f_code"] = "0" + fcode if fcode.size == 7
      scode = h_rec["sho_code"]
      h_rec["sho_code"] = format("%04d",scode.to_i) if scode.size < 4
      h_rec["kenri_sisu"] = (row["hyotei_sisu"].to_f * 1.006).round
      if land = find_by( f_code: h_rec["f_code"])
#        land.attributes = h_rec
        land.update(h_rec)
      else
#        next if h_rec[ "f_code" ].nil?
        land = new
        land.attributes = h_rec
        land.save!
      end
    end
    File.delete(file.path)
  end

  def self.updatable_attributes
    ["f_code", "toki_chimoku", "toki_men", "kijun_men", "zen_m2sisu", "hyotei_sisu", "sho_code"]
  end

end

app/controllers/lands_controller.rb
class LandsController < ApplicationController

  def show
    @lands = Land.where( sho_code: params[:id] )
  end

  def new
    @land = Land.new
  end

  def edit
    @land = Land.find(params[:id])
  end

  def index
    if sho = params[:sho_code]
      @lands = Land.where( sho_code: sho)
    else
      @lands = Land.all
    end
  end

  def create
    @land = Land.new(land_params)
 
    @land.save
#    redirect_to @land
p "route create->save"
    redirect_to land_path( id: @land.sho_code )
  end

  def update
    @land = Land.find(params[:id])

    if @land.update(land_params)
      view_context.recalc @land
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @land = Land.find(params[:id])
    @land.destroy
 
    redirect_to lands_path
  end
  
  def import
    Land.import(params[:file])
    redirect_to lands_path
  end

  def kenri
    @land = Land.find(params[:id])
    @land.update(kenri_sisu: (@land.hyotei_sisu.to_f * 1.006).round )
    redirect_to lands_path
  end

  private
    def land_params
      params.require(:land).permit(:f_code, :f_code_parent, :toki_chimoku,
      :toki_men, :zen_m2sisu, :kijun_men,:sho_code)
    end
end

app/helpers/lands_helper.rb
module LandsHelper
  def recalc fdata
    hyotei_sisu =  ( fdata.zen_m2sisu.to_f * fdata.kijun_men.to_f ).round
    kenri_sisu = (hyotei_sisu * 1.006).round
    fdata.update(hyotei_sisu: hyotei_sisu.to_s, kenri_sisu: kenri_sisu.to_s)
  end



end  #end of module

app/views/lands/_form.html.erb
<%= form_for @land do |f| %>
  <p>
    <%= f.label :f_code %><br>
    <%= f.text_field :f_code %>
  </p>

  <p>
    <%= f.label :f_code_p %><br>
    <%= f.text_field :f_code_parent %>
  </p>

 
  <p>
    <%= f.label :toki_chimoku %><br>
    <%= f.text_field :toki_chimoku %>
  </p>

  <p>
    <%= f.label :toki_men %><br>
    <%= f.text_field :toki_men %>
  </p>

  <p>
    <%= f.label :kijun_men %><br>
    <%= f.text_field :kijun_men %>
  </p>

  <p>
    <%= f.label :zen_m2sisu %><br>
    <%= f.text_field :zen_m2sisu %>
  </p>

    <%= f.label :sho_code %><br>
    <%= f.text_field :sho_code %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lands/_fude.html.erb
  <td>
    <%= obj.f_code %>
  </td>

  <td>
    <%= if obj.f_code_parent == "" || obj.f_code_parent.nil?
          "---"
        else
          obj.f_code_parent
        end
    %>
  </td>

  <td>
    <%= obj.toki_chimoku %>
  </td>
  <td>
    <%= obj.toki_men %>
  </td>
  <td>
    <%= obj.kijun_men %>
  </td>
  <td>
    <%= obj.zen_m2sisu %>
  </td>
  <td>
    <%= obj.hyotei_sisu %>
  </td>
  <td><%= obj.kenri_sisu %></td>
  <td>
    <%= if obj.sho_code.nil? || obj.sho_code == ''
          "---"
        else
#          "+++"
          link_to obj.sho_code, owner_path(obj.sho_code)
        end
    %>
  </td>
  <td>
    <%= if obj.owner.nil?
          "---"
        else
          obj.owner.shimei
        end
    %>
  </td>

app/views/lands/_fude_hd.html.erb
  <tr>
    <th>f_code</th>
    <th>f_code_p</th>
    <th>chimoku</th>
    <th>toki_men</th>
    <th>kijun_men</th>
    <th>sho_code</th>
    <th>shimei</th>
  </tr>

app/views/lands/edit.html.erb
<h1>新しい筆</h1>
<%= render 'form' %><br>

<%= link_to 'back', lands_path %>

app/views/lands/index.html.erb
<% provide(:title, "--従前地--") %>
<h1>従前地一覧</h1>
<%= form_tag lands_import_path, multipart: true do %>
<p>データ　インポート
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>
</p>

<%= form_tag( lands_path, :method => :get ) do %>
  <%= label :sho_code, "所有者を選択" %>
  <%= text_field_tag :sho_code %>
  <%= submit_tag "表示", name: "get_by_sho" %>
<% end %>
</p>


<%= link_to '筆を追加', new_land_path %> 
<br><br>
<% obj = Owner.find_by( sho_code: params[:sho_code]) %>
所有者: <%= obj.shimei if obj %><br><br>
<table border=1>
  <tr>
    <th>f_code</th>
    <th>f_code_p</th>
    <th>toki_chimoku</th>
    <th>toki_men</th>
    <th>kijun_men</th>
    <th>zen_m2sisu</th>
    <th>hyotei_sisu</th>
    <th>kenri_sisu</th>
    <th>sho_code</th>
    <th>shimei</th>
  </tr>
 
  <% @lands.each do |a| %>
    <tr>
      <%= render 'fude', obj: a %>
      <td><%= link_to '権利', kenri_land_path(a) %></td>
      <td><%= link_to '編集', edit_land_path(a) %></td>
      <td><%= link_to '削除', land_path(a),
              method: :delete,
              data: {confirm: '本当に削除しますか？'} %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'back', lands_path %>

app/views/lands/new.html.erb
<h1>新しい筆</h1>
<%= form_for :land, url: lands_path do |rec| %>
    <%= render 'form'  %><br>

<% end %>
<%= link_to 'back', lands_path %>

app/views/lands/show.html.erb
<h1>所有者別　従前地一覧</h1>
<table border=1>
  <%= render 'fude_hd' %>
  <% @lands.each do |land| %>
    <tr>
      <%= render 'fude', obj: land %>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', lands_path %>