config/routes.rb
Rails.application.routes.draw do
  get 'lands/index'
  post "lands/import"

  get 'kanchis/upload'
  post 'kanchis/upload_save'

  get 'owners/new'

  get 'welcome/index'

    resources :owners do
      resources :lands
    end
    resources :lands do
      member do
        get "kenri"
      end
    end
    resources :kanchis
    resources :kan_hyokas
    resources :kanchi_henkos
    root 'welcome#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  self.primary_key = "sho_code"
  has_many :lands, foreign_key: "sho_code"
#  belongs_to :land
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def create
    @owner = Owner.new(owner_params)
 
    @owner.save
    redirect_to @owner
  end

  def update
    @owner = Owner.find(params[:id])
 
    if @owner.update(owner_params)
      redirect_to @owner
    else
      render 'edit'
    end
  end

  def save2cvs
    render params[ :owner ].inspect
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy
 
    redirect_to owners_path
  end
  private
    def owner_params
      params.require(:owner).permit(:sho_code, :shimei, :jusho)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for @owner do |f| %>
  <p>
    <%= f.label :sho_code %><br>
    <%= f.text_field :sho_code %>
  </p>
 
  <p>
    <%= f.label :shimei %><br>
    <%= f.text_field :shimei %>
  </p>

  <p>
    <%= f.label :jusho %><br>
    <%= f.text_area :jusho %>
  </p>
 
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/owners/edit.html.erb
<h1>所有者を編集</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>所有者一覧</h1>
<%= link_to '所有者を追加', new_owner_path %> 
<table border=1>
  <tr>
    <th>Sho_code</th>
    <th>Shimei</th>
    <th>Jusho</th>
    <th>Note</th>
  </tr>
 
  <% @owners.each do |a| %>
    <tr>
      <td><%= a.sho_code %></td>
      <td><%= a.shimei %></td>
      <td><%= a.jusho %></td>
      <td><%= a.note %></td>
      <td><%= link_to 'Show', owner_path(a) %></td>
      <td><%= link_to 'Edit', edit_owner_path(a) %></td>
      <td><%= link_to 'Destroy', owner_path(a),
              method: :delete,
              data: {confirm: '本当に削除しますか？'} %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'back', owners_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>
<%= form_for :owner, url: owners_path do |f| %>
  <p>
    <%= f.label :sho_code %><br>
    <%= f.text_field :sho_code %>
  </p>
 
  <p>
    <%= f.label :shimei %><br>
    <%= f.text_field :shimei %>
  </p>

  <p>
    <%= f.label :jusho %><br>
    <%= f.text_area :jusho %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'back', owners_path %>

app/views/owners/show.html.erb
<p>
  <strong>Owner(sho_code):</strong>
  <%= @owner.sho_code %>
</p>
 
<p>
  <strong>Shimei:</strong>
  <%= @owner.shimei %>
</p>
<p>
  <strong>Jusho:</strong>
  <%= @owner.jusho %>
</p>


<% @owner.lands.where( f_code_parent: "parent" ).each do |a| %>
    <% #next if a.f_code_parent.nil? %>
  <table border=1>
    <%= render 'lands/fude_hd' %> 
    <tr>
      <%= render 'lands/fude', obj: a %>
      <td><%= link_to '詳細', lands_path(a) %></td>
      <td><%= link_to '編集', edit_land_path(a) %></td>
    </tr>
    <% a.children.each do |b| %>
      <tr>
        <%= render 'lands/fude', obj: b %>
        <td><%= link_to '詳細', lands_path(b) %></td>
        <td><%= link_to '編集', edit_land_path(b) %></td>
      </tr>
    <% end %>
  </table>
  <table border=1>
    <%= render 'kan_hyokas/kan_hyoka_hd' %> 
    <% a.kanchis.each do |kan| %>
      <% kan.kan_hyokas.each do |b| %>
        <%= render 'kan_hyokas/kan_hyoka', obj: b %>
      <% end %>
      <%= render 'kanchis/kanchi_hd' %>
      <%= render 'kanchis/kanchi', obj: kan %>
    <% end %>


  </table><br><br>

<% end %>
<br>
<%= link_to 'Back', owners_path %>
<pre>
  テキスト
  表示の
  テスト
  
  です。
</pre>