config/routes.rb
Rails.application.routes.draw do
  get 'lands/index'
  post "lands/import"

  get 'kanchis/upload'
  post 'kanchis/upload_save'

  get 'owners/new'

  get 'welcome/index'

    resources :owners do
      resources :lands
    end
    resources :lands do
      member do
        get "kenri"
      end
    end
    resources :kanchis
    resources :kan_hyokas
    resources :kanchi_henkos
    root 'welcome#index'

end

app/models/kanchi.rb
class Kanchi < ActiveRecord::Base
#  belongs_to :owner, foreign_key: "sho_code"
  self.primary_key = "kanchi_code"
  belongs_to :land
  has_many :kan_hyokas, foreign_key: "kanchi_code"
end

app/controllers/kanchis_controller.rb
class KanchisController < ApplicationController
  include KanchisHelper
  
  def show
    @kanchi = Kanchi.find(params[:id])
  end

  def new
    @kanchi = Kanchi.new
  end

  def edit
    @kanchi = Kanchi.find(params[:id])
  end

  def index
    @kanchis = Kanchi.order( 'updated_at DESC')
  end

  def create
   @kanchi = Kanchi.new(kanchi_params)
 
    @kanchi.save
    redirect_to @kanchi
 
  end

  def upload
    @kanchi = Kanchi.new
#    @kanchi.kanchi_code = "test_code"
#    @kanchi.save
  end

  def upload_save
#    render plain: upload_params[ :tmp_text ].inspect
    @kanchi = Kanchi.new
    arrRec = nil
    res = save_jikko( @kanchi, upload_params[ :tmp_text ], arrRec )
    #render plain: res.to_yaml
    redirect_to kanchis_path
  end

  def update
    @kanchi = Kanchi.find(params[:id])
 
    if @kanchi.update(kanchi_params)
      redirect_to @kanchi
    else
      render 'edit'
    end
  end


  def destroy
    @kanchi = Kanchi.find(params[:id])
    @kanchi.destroy
 
    redirect_to kanchis_path
  end

  private
    def kanchi_params
      params.require(:kanchi).permit(:kanchi_code, :f_code, :kenri_men, :kanchi_men, :kan_m2sisu)
    end
    def upload_params
      params.require(:kanchi).permit(:kanchi_code, :tmp_text)
    end

end

app/helpers/kanchis_helper.rb
require 'kanchis_sub/kanchi_kyotu'
require_dependency 'kanchis_sub/kanchi_read'
require 'spreadsheet'
require_dependency 'kanchis_sub/keisansho'
require 'yaml'
require 'pp'

module KanchisHelper	#換地変更と共用
	include Keisansho
	include KanchiKyotu
  def save_jikko kanAR, str, arrRec
		h_1n = nil
		if arrRec.nil?
	  	a = ExRead.new
		 	arrRec, h_1n = a.ex_get(str)
		end
	  arrTempData = []

    arrRec.each do | oneRec |			#2016/3/26
			res = nil
  	  kan_code = lot2code( oneRec.gokeiRec.block_num, oneRec.gokeiRec.lot_num)
			if h_1n
	    	oneRec.gokeiRec.h_1n = h_1n_filter( h_1n, oneRec.arrZenRec[0].fudecode )
			end
			if 	@kanchi = Kanchi.find_by( kanchi_code: kan_code )
				@kanchi.update( param_set(oneRec) )
#p "kanchi updated #{kan_code}"
			else
				kanAR=Kanchi.new
				kanAR.kanchi_code = kan_code
	  	  kanAR.f_code = oneRec.arrZenRec[0].fudecode
				kanAR.tmp_text = oneRec.to_yaml
				kanAR.save
#p "kanchi created #{kan_code}"
			end
		end
		land_parent_child arrRec[0] if arrRec[0].arrZenRec[0].sho_code != '5000'
		jikko arrRec
  end

	def param_set oneRec
		h={}
		h[:f_code] = oneRec.arrZenRec[0].fudecode
		h[:tmp_text] = oneRec.to_yaml
		h
	end

	def land_parent_child oneRec
		arr_fude = oneRec.arrZenRec.map do |r| r.fudecode end
		fcode_p = arr_fude.shift
		land = Land.find_by!(f_code: fcode_p)
		land.update( f_code_parent: 'parent' )
		arr_fude.each do |fcode|
			land = Land.find_by!(f_code: fcode)
			land.update( f_code_parent: fcode_p)
		end
	end

  def h_1n_filter h_1n, fcode
    h = {}
		h_1n.each do |key, val|
			next if key.nil?
			h[key] = val if key[/^#{fcode}/]
	  end
	  h
  end

	def lot2code blk, lot_full
		lot, eda = lot_full.split(/-/)
		eda = 0 if eda.nil?
		wk = format("%03d%03d%02d", blk, lot, eda)
	end

end

#2016/4/2 Moved to kanchi_kyotu.rb
#def kCode_to_kakuchiNo kanchi_code
#	p kanchi_code
#	kanchi_code[/^(...)(...)(..)/]
#  return kanchi_code if $1.nil? or $2.nil?
#	str = sprintf("%3dBL% 3dL ", $1.to_i, $2.to_i)
#  str += "-" + format("% 2d",$3.to_i) if $3.to_i > 0
#  str
#end

app/views/kanchis/_form.html.erb
<%= form_for @kanchi, url: dest do |f| %>
  <p>
    <%= f.label :kanchi_code %><br>
    <%= f.text_field :kanchi_code %>
  </p>
 
  <p>
    <%= f.label :f_code %><br>
    <%= f.text_field :f_code %>
  </p>

  <p>
    <%= (f.label :kenri_men) + 'テスト用' %><br>
    <%= f.text_field :kenri_men %>
  </p>

  <p>
    <%= f.label :kanchi_men %><br>
    <%= f.text_field :kanchi_men %>
  </p>

  <p>
    <%= f.label :kan_m2sisu %><br>
    <%= f.text_field :kan_m2sisu %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/kanchis/_kanchi.html.erb
 
  <td>
    <%= obj.attributes[ :id ] %>
  </td>
  <td>
    <%= kCode_to_kakuchiNo( obj.kanchi_code ) %>
  </td>
  <td>
    <%= obj.f_code %>
  </td>
  <td>
    <%= obj.kenri_men %>
  </td>
  <td>
    <%= obj.kanchi_men %>
  </td>
  <td>
    <%= obj.kan_m2sisu %>
  </td>

app/views/kanchis/_kanchi_hd.html.erb
  <tr>
    <th>id_unique</th>
    <th>kanchi_code</th>
    <th>f_code</th>
    <th>kenri_men</th>
    <th>kanchi_men</th>
    <th>kan_m2sisu</th>
  </tr>

app/views/kanchis/edit.html.erb
<h1>edit_kan_hyoka</h1>
<%= render 'form', dest:kanchi_path %><br>

<%= link_to 'back', kanchis_path %>

app/views/kanchis/index.html.erb
<% provide(:title, "--画地--") %>
<h1>Kanchi Data</h1>
<%= link_to 'add_kanchi', new_kanchi_path %> 
<br><br>
<table border=1>
  <%= Rails.root.to_s + "/xldata" %>
  <%= render 'kanchi_hd' %>
  <% @kanchis.order('updated_at DESC').each do |a| %>
    <tr>
      <%= render 'kanchi', obj: a %>
      <td><%= link_to '換地変更', kanchi_henkos_path({ get_exsisting: true, kanchi_henko: {f_code: a.f_code}}), method: :post %></td>
      <td><%= link_to '詳細', kanchi_path(a) %></td>
      <td><%= link_to '編集', edit_kanchi_path(a) %></td>
      <td><%= link_to '削除', kanchi_path(a),
              method: :delete,
              data: {confirm: '本当に削除しますか？'} %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'back', kanchis_path %>

app/views/kanchis/new.html.erb
<h1>New Kanchi</h1>

<%= render 'form', dest: kanchis_path  %><br>

<%= link_to 'back', kanchis_path %>

app/views/kanchis/show.html.erb
<% provide(:title, "--換地--詳細--") %>
<h1>Kanchi Details</h1><br>
<table border=1>
  <tr>
    <th>kanchi_code</th>
    <th>f_code</th>
    <th>kenri_men</th>
    <th>kanchi_men</th>
    <th>kan_m2sisu</th>
  </tr>
  <tr>
    <%= render 'kanchi', obj: @kanchi %>
  </tr>
</table>
<br>

<table border=1>
  <tr>
    <th>kanchi_code</th>
    <th>fugo</th>
    <th>men</th>
    <th>sisu</th>
  </tr>
 
  <% @kanchi.kan_hyokas.each do |a| %>
    <tr>
      <%= render 'kan_hyokas/kan_hyoka', obj: a %>
      <td><%= link_to '詳細', kan_hyokas_path(a) %></td>
      <td><%= link_to '編集', edit_kan_hyoka_path(a) %></td>
      <td><%= link_to '削除', kan_hyoka_path(a),
              method: :delete,
              data: {confirm: '本当に削除しますか？'} %></td>
    </tr>
  <% end %>
</table>

<%= render plain: debug(YAML::load( @kanchi.tmp_text )) %>







<%= link_to 'Back', kanchis_path %>

app/views/kanchis/upload.html.erb
<%= form_for @kanchi, :url => {:action => 'upload_save'} do |f| %>
  <p>
    <%= f.label :kanchi_code %><br>
    <%= f.text_field :kanchi_code %>
  </p>
 
  <p>
    <%= f.label :tmp_text %><br>
    <%= f.text_area :tmp_text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>